[INTERNAL] incorporate docu feedback
SAP-samples/s4hana-avc-ui-extension-template pull request #4
Opened 2023-02-10 17:21 UTC by florianstephan01

Documentation Update

2023-02-14 10:01 UTC, danielheffter requested changes
In general, your internal user ID is now part of the files (as author). I guess this should be better removed.

2023-02-14 10:01 UTC, danielheffter commented on doc/IMPLEMENTATION.md
> +> - When the namespace of the template is changed according to own name schemas, it need to be considered that the namespace is represented with <code>.</code> and <code>/</code> notation as separati
small typo: "..., it need**s**"

2023-02-14 10:01 UTC, danielheffter commented on webapp/libs/api/valuation/CharacteristicGroupClientObject.js
> +	 * is bound. Furthermore loading of Domain Values can be manally triggered (e.g. for an custom Value Help implementation) and
small typo: "manually"

2023-02-14 10:01 UTC, danielheffter commented on webapp/libs/api/valuation/CharacteristicGroupClientObject.js
> +	 * value assignments can be made. This is especially helpfull when it comes to own event handler implementations if the
small typo: "helpful"

2023-02-14 10:01 UTC, danielheffter commented on webapp/libs/api/valuation/CharacteristicGroupClientObject.js
> +		 * @param {string[]} aTechnicalValues - the technical values as strings
not sure if technical values are explained somewhere. In general, this is our internal naming of values which exist in the engine state and can be directly assigned without additional checks. Would it make a difference from your perspective to just name them values?

2023-02-14 10:01 UTC, danielheffter commented on webapp/libs/api/valuation/control/CharacteristicContextContainer.js
> +				 * Property - Whether domain values can be kept in case of a value assignment (performance optimization for independent Characteristics) - optional, default is <code>false</code>
I would make it even clearer by saying domain values are only loaded once and not updated ... values can be kept can potentially be misunderstood how long (until next validation?)

2023-02-14 10:01 UTC, danielheffter commented on webapp/libs/api/valuation/control/CharacteristicContextContainer.js
> +				 * Property - Whether the container should load Domain Values - optional, default is <code>false</code>
I would also add here: Whether the container should load Domain Values with the loading of characteristics. This is independent of value helps.

2023-02-15 08:43 UTC, florianstephan01 commented on doc/IMPLEMENTATION.md
> +> - When the namespace of the template is changed according to own name schemas, it need to be considered that the namespace is represented with <code>.</code> and <code>/</code> notation as separati
fixed

2023-02-15 08:43 UTC, florianstephan01 commented on webapp/libs/api/valuation/CharacteristicGroupClientObject.js
> +	 * is bound. Furthermore loading of Domain Values can be manally triggered (e.g. for an custom Value Help implementation) and
fixed

2023-02-15 08:44 UTC, florianstephan01 commented on webapp/libs/api/valuation/CharacteristicGroupClientObject.js
> +	 * value assignments can be made. This is especially helpfull when it comes to own event handler implementations if the
fixed

2023-02-15 08:44 UTC, florianstephan01 commented on webapp/libs/api/valuation/control/CharacteristicContextContainer.js
> +				 * Property - Whether domain values can be kept in case of a value assignment (performance optimization for independent Characteristics) - optional, default is <code>false</code>
fixed

2023-02-15 08:44 UTC, florianstephan01 commented on webapp/libs/api/valuation/control/CharacteristicContextContainer.js
> +				 * Property - Whether the container should load Domain Values - optional, default is <code>false</code>
fixed

2023-02-15 08:45 UTC, florianstephan01 commented
Removed the author tag

2023-02-15 08:45 UTC, florianstephan01 commented on webapp/libs/api/valuation/CharacteristicGroupClientObject.js
> +		 * @param {string[]} aTechnicalValues - the technical values as strings
Leave technical values after discussion.

2023-02-15 08:46 UTC, merged